#Conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv_db
spring.datasource.username=postgres
spring.datasource.password=edu123

#Configuração do JPA
#cria ou atualiza as tabelas automaticamente baseadas nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format_sql=true

#Porta do servidor WEB
server.port=8080