spring.datasource.url=jdbc:postgresql://ep-jolly-band-acy65tuw.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tw3cnNKl9qRU
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=a3aYNGh5FwmoUisUaQU/L9Ye6ouTxIN/C8te7bHkCOc=